### ISSUE TITLE
Feature Request - Work with Primeng 10+ multi filter on single column

### ISSUE THREAD

**Issue by kingbe01** [Kusumoto/PrimeNG.TableFilter#14]
As far as I can tell this does not allow for primeng's new multi filter on a single column. I apologize if I am mistaken but prime's new structure looks like the below on the front end. 

"filters": {
        "Active": [ // now an array instead of single object for each column
            {
                "value": null,
                "matchMode": "startsWith",
                "operator": "and"
            }
        ],

**Comment by Kusumoto** [comment]
Hi, thank you for your feature request.

Can you tell me about PrimeNG docs reference or something else for defined this.

**Comment by kingbe01** [comment]
I believe starting with Primeng 10 they started to allow multiple filters on a single column.  This forced them to change the filter object to handle an array of filter per column like shown above. I cannot find anymore documentation other than what I just shared. Thanks for any help you can give.

![Screen Shot 2021-04-22 at 7 49 26 AM](https://user-images.githubusercontent.com/2152828/115717308-aadfe880-a33f-11eb-8d75-7d0e4c4b7051.png)

![Screen Shot 2021-04-22 at 7 50 19 AM](https://user-images.githubusercontent.com/2152828/115717320-b03d3300-a33f-11eb-99e8-2ca4888259ce.png)

**Comment by Kusumoto** [comment]
I find the solution for resolve this feature, your feature request has be release in next version.

**Comment by kingbe01** [comment]
Thank you! I will check it out today.

**Comment by kingbe01** [comment]
Do you have an estimate with the next release will be? Thank again for taking care of this.

**Comment by Kusumoto** [comment]
Your feature request has release in version 2.0
