### ISSUE TITLE
Feature request - Total call separate. 

### ISSUE THREAD

**Issue by kingbe01** [Kusumoto/PrimeNG.TableFilter#20]
Thank you for updating your package to use the new filtering structure. we have tested and it works great! We have on other need - the ability to make separate calls for the data and the total instead of doing both together. We propose a new param on the PrimengTableFilter extension (bool includeTotal), and then a new  extension PrimengTableFilterTotal that just returns an Int.  Once again thank you for considering taking a look.

**Comment by fanningmsf** [comment]
@Kusumoto I have a proposed set of changes (to both the library and the unit tests) that I would like to send you to address the latest request from @kingbe01 (from our team).  I am unable to push to this project (and submit a Pull Request) as it tells me "Remote: Permission to Kusumoto/PrimeNG.TableFilter.git denied to fanningmsf" so I'm guessing that you have this locked down in your project.  Therefore I am going to upload a zip file of my changes.  Here is a summary list of the changes:

1.) Added ModeEnumeration and corresponding ApplyFilters overloads to support retrieval of just the data, just the total, or both in the result.
2.) Added support for null values. Created new IsNullOrEmptyOperator.
3.) Prevents duplicate lambda expression from being added to _context.Expressions.
4.) Added new unit tests and test data

Thank you for your consideration.

[PrimeNG.TableFilter-modified-fanningmsf.zip](https://github.com/Kusumoto/PrimeNG.TableFilter/files/6591906/PrimeNG.TableFilter-modified-fanningmsf.zip)

**Comment by Kusumoto** [comment]
Hi, Thank you for your feature request and your PR.

First one, you cannot direct access to this repository, Please follow this instruction.

1. Fork this repository to your account
2. Checkout you fork repository to your local computer.
3. Create branch for develop your feature.
4. After complete you feature, commit your feature and push to you fork repository.
5. Create PR from you fork repository compare with my repository.
6. Complete detail for your PR.
7. Waiting for review

**Comment by fanningmsf** [comment]
Thank you. I will do that as soon as I get a chance.

 

===========

Mike Fanning

***@***.*** ***@***.***>
