### ISSUE TITLE
Feature request: implement multiple sort into the TableFilter

### ISSUE THREAD

**Issue by verbraucher** [Kusumoto/PrimeNG.TableFilter#6]
Hey there,
first I want to thank you for this great plugin!

Is it possible to implement the multiple sorting of primeNg in the upcoming version?

Here is the snippet of the lazyload-event from typesrcipt:

```
interface LazyLoadEvent {
...
**multiSortMeta?: SortMeta[];**
...
}
```

**Comment by Kusumoto** [comment]
Hi @verbraucher 
Thank you for this feature request.
I will implement this in next version.

**Comment by Kusumoto** [comment]
This feature is added in #7 and release in version 1.0.3
